### ISSUE TITLE
Bind to device

### ISSUE THREAD

**Issue by mweinelt** [ffnord/mesh-announce#22] opened 2017-07-19 14:34 UTC
Currently the ThreadingUDPServer binds globally to `:::1001`. This is problematic when multiple mesh-announce instances for different batman meshes are to be run.

<s>I'm not sure what the `--iface` parameter needs `action=append` for, but I suggest removing that and binding to the single interface given.</s>

In https://github.com/ffnord/mesh-announce/blob/master/respondd.py#L77 we likely need to bind to a single interface
```
        (args.group, args.port, 0, socket.if_nametoindex(args.iface)),
```
as proposed by kpanic in https://github.com/ff3l/respyndd/blob/master/respondd.py#L81

**Comment by jplitza** [comment] 2017-07-30 19:56
OTOH, binding only to bat0 (or the bridge above) breaks the status pages of neighbouring nodes, as they need to query the name via the lower mesh interface (VPN, Wifi, LAN) IIRC. See also #21.

**Comment by genofire** [comment] 2017-07-30 20:05
That is not the Problem, the problem is, that the daemon bind on "" which mean all interfaces. (Before It listen with the interfaces at the multicast group).
On this way it is not possible to run multiple instance for more then one side of this daemon on the same host.

**Comment by jplitza** [comment] 2017-07-30 20:19
I know that that is the problem reported, but listening only on one interface causes other problems I mentioned above.

**Comment by mweinelt** [comment] 2017-10-19 01:58
So is there a solution to this issue?

**Comment by TobleMiner** [comment] 2019-09-07 22:57
Should be fixed by https://github.com/ffnord/mesh-announce/pull/47

**Closed** 2019-09-15 17:45 UTC
